Update nav menu
pytorch/pytorch_sphinx_theme pull request #54
Opened 2019-10-15 20:20 UTC by Pat878

This PR updates the main navigation menu.

- A link to the Mobile page has been added.
- The Ecosystem dropdown has been added.
- The Resources dropdown has been added.

Here's a preview of the updates: https://5d9f5672ff54b94fadd153d4--shiftlab-pytorch-docs.netlify.com/.

2019-10-15 23:38 UTC, jlin27 commented
I tried building this locally following [these steps](https://fb.quip.com/HhcJAXRvbq9H) to install PR#54 for local testing and I'm getting the weird rendering: 
![image](https://user-images.githubusercontent.com/8042156/66877346-fa36a300-ef69-11e9-8d28-f03754972839.png)

My local steps to reproduce:
1. Cloned pytorch/pytorch repo
2. Removed github pytorch_sphinx_theme install from docs/requirements.txt
3. Installed theme locally for PR:54 via https://fb.quip.com/HhcJAXRvbq9H
4. `make html` and preview index.html

2019-10-15 23:45 UTC, jlin27 commented
It looks like the extra text is what was meant to be in the drop down menu - 
"...pre-trained models" and "Tools & Libraries" are from Ecosystem
and 
"questions answered" and "About" are from Resources

Was it the addition of the ecosystem-dropdown and the resources-dropdown in the [layout.html](pytorch_sphinx_theme/layout.html) files that's causing this issue since the original nav in the docs page doesn't have a dropdown option?

2019-10-15 23:46 UTC, jlin27 requested changes

2019-10-15 23:46 UTC, jlin27 commented on pytorch_sphinx_theme/layout.html
> +            <div class="ecosystem-dropdown">
This section seems to be causing the render issues cause dropdown wasn't allowed before

2019-10-15 23:46 UTC, jlin27 commented on pytorch_sphinx_theme/layout.html
> +            </div>
This section seems to be causing the render issues cause dropdown wasn't allowed before

2019-10-16 13:46 UTC, Pat878 commented
@jlin27 I requested access to the quip link you shared so that I can see the steps you're following to build the docs with the theme. 

From the screenshot you shared, it looks like the CSS I added in my PR is not being added to your local build--that's why the dropdown isn't appearing correctly. If you look at the generated `theme.css` file from the preview link I shared, you can see that the CSS is added correctly: https://5d9f5672ff54b94fadd153d4--shiftlab-pytorch-docs.netlify.com/_static/css/theme.css. (Search for "ecosystem-dropdown".) The `theme.js` file is updated as well: https://5d9f5672ff54b94fadd153d4--shiftlab-pytorch-docs.netlify.com/_static/js/theme.js. (Search for "mainMenuDropdown".) When building locally with my branch you should see these updated files appear in the `pytorch_sphinx_theme/static` folder.

If it's easier for me to include the updated `theme.css` and `theme.js` in my PR, I can do that. However, I didn't include those files since they are usually generated separately by your team.

2019-10-17 12:54 UTC, Pat878 commented
@jlin27 I tried to build the docs following the steps you listed, and I can confirm that with your approach the updates I made won't appear correctly. Your steps assume that `theme.css` and `theme.js` are present in the PR. Since I didn't include those files in my PR, your build won't pick up the CSS changes I've made. Please let me know if you are changing the way you deploy the docs and if I should now include `theme.css` and `theme.js` in my PRs going forward.

2019-10-17 14:40 UTC, brianjo commented
> @jlin27 I tried to build the docs following the steps you listed, and I can confirm that with your approach the updates I made won't appear correctly. Your steps assume that `theme.css` and `theme.js` are present in the PR. Since I didn't include those files in my PR, your build won't pick up the CSS changes I've made. Please let me know if you are changing the way you deploy the docs and if I should now include `theme.css` and `theme.js` in my PRs going forward.

Hey @Pat878, thanks for your work on this. Yes, it would be great if you could add all the updates to your PRs. We've always built docs using this install method, so getting everything into the new PRs would be best.

2019-10-17 14:54 UTC, patmellon commented
@brianjo Sounds good. I updated the PR to include the files.

2019-10-17 15:15 UTC, brianjo commented
Tested functionality locally. Looks good. Thanks @Pat878!
![Screenshot 2019-10-17 08 14 31](https://user-images.githubusercontent.com/1500149/67022567-47279000-f0b6-11e9-9655-cbf02a6e7302.png)

2019-10-17 15:15 UTC, merged